import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { NavBar } from '@/components/NavBar';

const montserrat = Montserrat({ 
  subsets: ['latin'],
  variable: "--font-mont" 

});

export const metadata: Metadata = {
  title: 'Emanuel Henrique | Software Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={`${montserrat.className} w-full min-h-screen`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
